-- PERSON PERSON PRIMEIRO NOME DO TITULO MIDON NAME, QUE TENHA MISTER, E TBM A NO MIDON NAME..

SELECT FirstName, Title, MiddleName FROM Person.Person
WHERE Title = 'Mr.'
--577
UNION
SELECT FirstName, Title, MiddleName FROM Person.Person
WHERE MiddleName = 'a'
--1319
AND Title IS NOT NULL 
AND MiddleName IS NOT NULL
ORDER BY FirstName

-- MOSTRAR ,MEDIA MENSAL DE VALORES VENDIDOS
--SALES.SALESORDERHEADER
SELECT * FROM Sales.SalesOrderHeader

SELECT AVG(TotalDue), DATEPART(MONTH, OrderDate) MÊS
FROM Sales.SalesOrderHeader
GROUP BY DATEPART(MONTH, OrderDate)
ORDER BY 2


SELECT AVG(TotalDue), DATEPART(YEAR, OrderDate) MÊS
FROM Sales.SalesOrderHeader
GROUP BY DATEPART(YEAR, OrderDate)
ORDER BY 2

-- QUAIS SÃO OS PRODUTOS QUE ESTÃO ACIMA DA MEDIA DE VENDAS 
-- PRODUCTION.PRODUCT - ID, LISTPRICE
-- SUB SELECT - PRODUCTION.PRODUCT

SELECT ProductID, ListPrice FROM Production.Product AS P
WHERE ListPrice > (SELECT AVG (ListPrice) FROM Production.Product) 


