USE AdventureWorks2012

-- QUANTOS PRODUTOS VERMELHOS TEM PREOÇO ENTRE 500 E 1000

SELECT COUNT(*) AS 'PRODUTOS VERMELHOS'FROM Production.Product
WHERE COLOR = 'RED'
AND ListPrice BETWEEN 500 AND 1000



-- PRODUTOS QUE TEM ESSA SEQ DE CARACTER NO NOME ROAD

SELECT * FROM Production.Product
WHERE NAME LIKE '%ROAD%'


-- PARA CALCULAR 
SELECT COUNT(NAME) FROM Production.Product
WHERE NAME LIKE '%ROAD%'

SELECT * FROM SALES.SalesOrderDetail

-- TOP 10 
SELECT TOP 10 * FROM SALES.SalesOrderDetail


-- DO MENOR PARA MAIOR 
SELECT TOP 10 * FROM SALES.SalesOrderDetail ORDER BY LineTotal ASC --DESC
SELECT * FROM SALES.SalesOrderDetail


-- somar 
SELECT TOP 10 SUM(LINETOTAL) AS TOTALVENDAS FROM Sales.SalesOrderDetail


--MINIMA MAXIMA MIN MAX
SELECT TOP 10 MAX(LINETOTAL) AS TOTALVENDAS FROM Sales.SalesOrderDetail


-- AVG 

SELECT AVG(LINETOTAL) AS TOTALVENDAS FROM Sales.SalesOrderDetail



-- CALCULAR E AGRUPAR 

SELECT FirstName,COUNT(FirstName) AS QTDE FROM Person.Person
GROUP BY FirstName


-- PROCURA POR OFERTA AGRUPAMENTO EM ORDEM 

SELECT SpecialofferID, SUM(UnitPrice) AS 'TOTAL DE VENDAS' FROM Sales.SalesOrderDetail
GROUP BY SpecialofferID
ORDER BY SpecialofferID ASC -- OU DESC 

-- SOMA 
SELECT SpecialofferID, SUM(UnitPrice) AS 'TOTAL DE VENDAS' FROM Sales.SalesOrderDetail
GROUP BY SpecialofferID
ORDER BY SUM(UnitPrice) DESC -- OU DESC 


-- QUANTOS PRODUTOS FORAM VENDIDOS ATE HJ 

SELECT ProductID, COUNT(ProductID) AS 'QTDE DE PRODUTOS ATÉ HOJE' FROM Sales.SalesOrderDetail
GROUP BY ProductID

-- MEDIA DE PREÇO DOS PRUTOS QUE SÃO PRATA 

SELECT COLOR, AVG (ListPrice)FROM Production.Product
WHERE  COLOR = 'SILVER'
GROUP BY COLOR 

SELECT MiddleName, COUNT(MiddleName)  QTDE FROM Person.Person 
GROUP BY MiddleName

/* Desafios 
1- QUAL A MEDIA QUE CADA PRODUTO É VENDIDO [SALESORDEDETAIL]

2- QUAIS OS 10 PRODUTOS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA 
AGRUPADOS POR PRODUTO DO MAIOR PARA O MENOR [SALESORDERDETAIL]

3- QUANTOS PRODUTOS E QUAL A QTDE MEDIA DE PRODUTOS TEMOS CADASTRADOS NAS ORDENS DE SERVIÇO
(WORKORDER) - AGRUPAR PELO ID DO PRODUTO [PRODUCTION.WORKORDER]
 */
 
 SELECT ProductID, AVG(OrderQty) FROM sales.SalesOrderDetail
 GROUP BY ProductID

 SELECT TOP 10 ProductID, SUM(LineTotal) FROM sales.SalesOrderDetail
 GROUP BY ProductID
 ORDER BY SUM(LineTotal) DESC 


 SELECT ProductId, COUNT(ProductID) AS QTDE, AVG(OrderQty) As MEDIA
 FROM Production.WorkOrder
 GROUP BY ProductId


SELECT FirstName, COUNT(FirstName) 
FROM Person.Person
WHERE FirstName LIKE 'A%'
GROUP BY FirstName
HAVING COUNT(FirstName) > 10


-- AGRUPAR OS PRODUTOS[PRODUCTID] POR VENDAS TOTAIS[LINETOTAL] ENTRE 162K E 500K

SELECT ProductID, SUM(LineTotal) AS TOTAL
FROM Sales.SalesOrderDetail
GROUP BY ProductID 
HAVING SUM(LineTotal) BETWEEN 162000 AND 500000


--QUAIS PRODUTOS NÃO ESTÃO TRAZENDO EM MEDIA VENDAS DE UM MILHÃO NO TOTAL.
SELECT ProductID, AVG(LineTotal) AS TOTAL
FROM Sales.SalesOrderDetail
GROUP BY ProductID 
HAVING AVG(LineTotal) < 1000